name: I Have a Question
description: You aren't reporting a bug, etc., just asking a question.
title: "[Question] "  
labels: question  
assignees: [deanwampler,bnayahu]
projects: []
body:
- type: checkboxes
  attributes:
    label: Is there an existing similar question?
    description: Please search to see if another issue covers your question.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: |
      Describe your question. Where applicable, please provide:
      * What you are trying to accomplish
      * What you have tried so far
      * Any relevant code or doc  
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Context
    description: |
      Add any other context or screenshots about the documentation/website change here.
  validations:
    required: false
